(function () {
  "use strict";

  const DATA = window.SCAFFOLD_DATA;
  if (!DATA) throw new Error("Scaffold Seeds data must load before Build 3 data.");

  const ALL_YEARS = ["EYFS", "Year 1", "Year 2", "Year 3", "Year 4", "Year 5", "Year 6"];
  const KS12 = ALL_YEARS; // EYFS routes use early-learning equivalents; statutory subject programmes begin later
  const KS2 = ALL_YEARS; // non-statutory early-language enrichment remains available; statutory study begins at KS2

  const entry = (title, years, objectives, vocabulary, misconceptions, barriers) => ({
    title, years, objectives, vocabulary, misconceptions, barriers
  });

  const additionalSubjects = [
    {
      id: "art", name: "Art and Design", short: "Art", colour: "#8b6d76",
      summary: "Observe, experiment and make deliberate visual choices while developing a personal response.",
      principles: ["looking precedes labelling", "materials are tested, not merely used", "artist knowledge opens choices", "outcomes need not look identical"],
      entries: [
        entry("Drawing and observation", ALL_YEARS, ["Use observation to notice and record shape, line, tone, texture and proportion", "Develop ideas through drawing and sketchbook exploration"], ["line", "tone", "texture", "proportion", "observation"], ["Observation means copying an outline", "A successful drawing must look photographic"], ["attention", "representation", "self-monitoring"]),
        entry("Colour, paint and surface", ALL_YEARS, ["Explore colour relationships, mixing, application and surface for an intended effect", "Make and explain purposeful colour choices"], ["hue", "tone", "tint", "shade", "contrast"], ["Primary colours always produce a bright secondary colour", "Colour choice has one correct answer"], ["conceptual", "planning", "vocabulary"]),
        entry("Sculpture, textiles and materials", ALL_YEARS, ["Explore how material properties and processes can communicate an idea", "Select, combine and evaluate materials"], ["form", "structure", "surface", "join", "material"], ["The first material chosen must be kept", "Decoration can replace structural thinking"], ["planning", "self-monitoring", "knowledge"]),
        entry("Artists and creative connections", KS12, ["Make thoughtful connections between artists, works, contexts and personal making", "Compare artistic choices without ranking cultures or styles"], ["artist", "context", "intention", "influence", "interpretation"], ["Artists work in one recognisable style", "Learning from an artist means copying the outcome"], ["reasoning", "comparison", "knowledge"])
      ]
    },
    {
      id: "design-technology", name: "Design and Technology", short: "D&T", colour: "#8a7655",
      summary: "Design purposeful products for users, make with technical understanding, test and improve against criteria.",
      principles: ["begin with user and purpose", "criteria make success testable", "making follows design decisions", "evaluation leads to redesign"],
      entries: [
        entry("User, purpose and design criteria", KS12, ["Identify a user and purpose, then create meaningful design criteria", "Generate and communicate more than one design possibility"], ["user", "purpose", "criteria", "function", "constraint"], ["A design criterion describes decoration", "The first idea is the final design"], ["planning", "reasoning", "organisation"]),
        entry("Structures and mechanisms", KS12, ["Use structural or mechanical knowledge to make a product work", "Select and test components, joins and mechanisms"], ["structure", "stable", "lever", "linkage", "mechanism"], ["More material always makes a structure stronger", "A mechanism is decoration that moves"], ["conceptual", "representation", "self-monitoring"]),
        entry("Materials and manufacture", KS12, ["Select tools, materials and techniques for functional reasons", "Plan and carry out a safe, accurate making sequence"], ["property", "measure", "mark", "cut", "join"], ["Materials are interchangeable", "A neat product necessarily meets its specification"], ["knowledge", "planning", "working-memory"]),
        entry("Test, evaluate and improve", KS12, ["Test a product against design criteria and evidence", "Use findings to propose and make purposeful improvements"], ["test", "evidence", "evaluate", "specification", "improve"], ["Evaluation is saying whether the product is liked", "Improvement always means adding a feature"], ["self-monitoring", "reasoning", "writing"])
      ]
    },
    {
      id: "music", name: "Music", short: "Music", colour: "#6e728c",
      summary: "Listen, perform and compose through sound; use notation only where it supports musical thinking.",
      principles: ["sound comes before extensive writing", "pulse and rhythm are distinct", "notation represents music rather than replacing it", "rehearsal is deliberate improvement"],
      entries: [
        entry("Pulse, rhythm and metre", ALL_YEARS, ["Maintain a shared pulse and perform or create rhythmic patterns", "Distinguish pulse from rhythm through listening and performance"], ["pulse", "rhythm", "beat", "metre", "pattern"], ["Pulse and rhythm are the same", "A rest means the pulse stops"], ["attention", "conceptual", "working-memory"]),
        entry("Pitch, melody and notation", ALL_YEARS, ["Hear, perform and represent changes in pitch", "Use graphic or staff notation to support performance and composition"], ["pitch", "melody", "contour", "notation", "phrase"], ["A higher note is necessarily louder", "Notation is the music itself"], ["representation", "vocabulary", "self-monitoring"]),
        entry("Listening and appraisal", ALL_YEARS, ["Notice musical features and explain their contribution to effect and context", "Compare performances or pieces through shared musical criteria"], ["timbre", "texture", "dynamics", "tempo", "structure"], ["Listening answers are only personal preference", "One instrument always has one timbre"], ["attention", "reasoning", "comparison"]),
        entry("Composition and performance", ALL_YEARS, ["Select, organise, rehearse and refine musical ideas", "Perform with awareness of ensemble, audience and expressive intent"], ["motif", "structure", "rehearse", "ensemble", "expression"], ["Composition must begin with notation", "Rehearsal means repeating without changing"], ["planning", "self-monitoring", "organisation"])
      ]
    },
    {
      id: "physical-education", name: "Physical Education", short: "PE", colour: "#5f8178",
      summary: "Develop physical competence, tactical awareness and reflective practice through movement with minimal reading load.",
      principles: ["one strong movement cue beats dense instructions", "practice must preserve active movement time", "feedback names an observable feature", "tactics require perception and decision"],
      entries: [
        entry("Fundamental movement and skill", ALL_YEARS, ["Develop control, balance, coordination and efficient movement", "Apply one observable cue to improve a movement pattern"], ["balance", "control", "coordination", "accuracy", "fluency"], ["Trying harder always improves technique", "A cue should describe every body part"], ["attention", "self-monitoring", "working-memory"]),
        entry("Games and tactical decision-making", KS12, ["Select and apply tactics in response to space, teammates and opposition", "Reflect on the effect of a tactical choice"], ["space", "support", "possession", "transition", "tactic"], ["The strongest player should always keep possession", "A tactic is a fixed move regardless of context"], ["reasoning", "attention", "planning"]),
        entry("Dance and gymnastics", ALL_YEARS, ["Create, perform and refine linked movement sequences", "Use action, space, dynamics and relationships intentionally"], ["sequence", "level", "direction", "dynamic", "transition"], ["A longer sequence is automatically better", "Copying a model removes the need for composition"], ["planning", "organisation", "self-monitoring"]),
        entry("Health, fitness and safe participation", KS12, ["Recognise how activity affects the body and participate safely", "Set and review a specific physical challenge"], ["stamina", "strength", "flexibility", "warm-up", "recovery"], ["Fitness is one fixed trait", "Breathlessness alone shows unsafe exercise"], ["knowledge", "self-monitoring", "vocabulary"])
      ]
    },
    {
      id: "languages", name: "Languages", short: "Languages", colour: "#7f6f8f",
      summary: "Hear, speak, read and write in another language through accurate sound, pattern, interaction and cultural context.",
      principles: ["listen before relying on the written form", "pronunciation uses the target language sound system", "substitution should create meaning", "accuracy and communication develop together"],
      entries: [
        entry("Sounds and spelling", KS2, ["Discriminate, reproduce and connect familiar sounds and spellings", "Read familiar words aloud with increasingly accurate pronunciation"], ["sound", "spelling", "syllable", "stress", "intonation"], ["English letter values transfer directly", "An English pronunciation respelling is more accurate than audio modelling"], ["reading", "attention", "vocabulary"]),
        entry("Vocabulary and retrieval", KS2, ["Understand and retrieve high-frequency words and phrases in context", "Use word patterns to infer or remember meaning"], ["cognate", "root", "gender", "article", "phrase"], ["Cognates always have identical meanings", "A translated word is known after one encounter"], ["knowledge", "vocabulary", "self-monitoring"]),
        entry("Sentence building and grammar", KS2, ["Manipulate familiar grammatical patterns to communicate new meanings", "Notice and apply agreement or verb patterns"], ["verb", "noun", "agreement", "word order", "pattern"], ["English word order can be translated one word at a time", "Every noun or verb follows one pattern"], ["conceptual", "writing", "representation"]),
        entry("Interaction and culture", KS2, ["Take part in short exchanges, listening and responding appropriately", "Explore cultural contexts without reducing places to stereotypes"], ["question", "response", "register", "culture", "context"], ["A memorised monologue is a conversation", "One example represents every speaker or community"], ["explanation", "reading", "reasoning"])
      ]
    },
    {
      id: "religious-education", name: "Religious Education", short: "RE", colour: "#8a705f",
      summary: "Explore religion and non-religion through substantive knowledge, ways of knowing and personal reflection. Content must follow the school's applicable syllabus.",
      principles: ["use the school's locally applicable syllabus", "represent internal diversity", "separate evidence, interpretation and personal reflection", "never fabricate testimony"],
      entries: [
        entry("Belief, practice and identity", KS12, ["Explore relationships between beliefs, practices, communities and identity using the applicable RE syllabus", "Recognise diversity within and between religious and non-religious worldviews"], ["belief", "practice", "identity", "tradition", "worldview"], ["All members of a tradition believe and practise identically", "A practice has one meaning in every context"], ["knowledge", "comparison", "vocabulary"]),
        entry("Texts, artefacts and interpretation", KS12, ["Ask contextual questions of a text, object or practice", "Compare interpretations without treating one item as speaking for an entire tradition"], ["sacred", "artefact", "interpretation", "authority", "context"], ["An artefact explains itself", "A sacred text has one uncontested interpretation"], ["reasoning", "reading", "knowledge"]),
        entry("Questions, reasons and lived experience", KS12, ["Discuss philosophical and ethical questions using reasons and examples", "Distinguish learned examples from personal disclosure"], ["reason", "evidence", "ethics", "experience", "perspective"], ["Every question has one religious answer", "Pupils should represent a community through personal disclosure"], ["reasoning", "explanation", "comparison"])
      ]
    },
    {
      id: "pshe", name: "PSHE and Relationships", short: "PSHE", colour: "#6f8171",
      summary: "Teach age-appropriate relationships, health, safety and decision-making through scenarios that never require public personal disclosure.",
      principles: ["use safeguarding-sensitive scenarios", "never require personal disclosure", "teach routes to help, not therapeutic intervention", "follow the school's policy and statutory guidance"],
      entries: [
        entry("Relationships and communication", KS12, ["Recognise respectful communication, boundaries and ways to repair everyday relationship difficulties", "Practise language for seeking help or responding safely"], ["respect", "boundary", "consent", "repair", "trusted adult"], ["Being kind means accepting every request", "A pupil must disclose a personal example to show understanding"], ["vocabulary", "reasoning", "explanation"]),
        entry("Health, emotions and strategies", KS12, ["Develop precise emotion and health vocabulary and select proportionate everyday strategies", "Recognise when and how to seek adult help"], ["emotion", "strategy", "health", "support", "help-seeking"], ["Emotions are simply positive or negative", "A classroom strategy replaces professional support"], ["vocabulary", "self-monitoring", "planning"]),
        entry("Online safety and decisions", KS12, ["Evaluate age-appropriate online scenarios and identify safe actions", "Explain how and why to seek help, report or pause"], ["private", "public", "report", "block", "pressure"], ["Online harm is always caused by strangers", "Reporting is the same as getting someone into trouble"], ["reasoning", "planning", "knowledge"]),
        entry("Goals and transition", KS12, ["Set, plan and review a manageable goal", "Identify helpful people, routines and next actions during change"], ["goal", "step", "strategy", "review", "transition"], ["A good goal is vague and motivational", "Needing support means the goal was failed"], ["planning", "self-monitoring", "organisation"])
      ]
    }
  ];

  additionalSubjects.forEach(subject => {
    if (!DATA.subjects.some(item => item.id === subject.id)) DATA.subjects.push(subject);
  });

  const profile = (id, name, keywords, disciplinary, threshold, vocabulary, misconceptions, representations, families) => ({
    id, name, keywords, disciplinary, threshold,
    prerequisites: ["relevant prior experience", "secure language for the immediate task", "a clear purpose for the subject action"],
    smallSteps: ["notice the relevant feature", "try or represent one purposeful choice", "compare its effect", "refine using evidence", "explain the decision"],
    vocabulary, misconceptions,
    assessment: ["Ask the pupil to justify one choice", "Change one condition and observe whether the principle transfers"],
    families, questions: ["Which choice must remain with the pupil?", "What is the smallest cue that makes the next subject action possible?"], representations
  });

  const brains = {
    art: {
      identity: "Art develops looking, material knowledge, visual language, experimentation and intentional making.",
      bigIdeas: ["Visual elements communicate", "Materials invite and constrain choices", "Artists respond to contexts", "Making and reflection are iterative"],
      knowledgeTypes: ["visual", "material", "procedural", "contextual"], progression: ["sensory noticing", "controlled exploration", "deliberate selection", "personal intention and refinement"],
      teacherReminders: ["Do not make every outcome identical", "Keep sketchbook prompts brief enough to protect making time"],
      profiles: [
        profile("looking", "Looking and noticing", ["look", "observe", "draw", "artist", "compare"], "Attend to visual evidence and form a personal, defensible interpretation.", "Naming a feature is different from explaining its visual effect.", ["line", "tone", "texture", "shape", "composition"], ["Looking means listing objects", "There is one correct interpretation"], [{ name: "Visual element lens", use: "when attention needs directing without prescribing an outcome", avoid: "when it becomes a checklist for identical work" }], ["visual-thinking", "discussion", "reasoning"]),
        profile("making", "Materials and making", ["material", "paint", "sculpt", "colour", "texture"], "Explore properties, select processes and refine an intention through making.", "A material choice should serve an intention rather than decorate a pre-decided outcome.", ["material", "process", "effect", "intention", "refine"], ["The first attempt must be kept", "More techniques make work better"], [{ name: "Test–notice–choose strip", use: "during material exploration", avoid: "as a recipe for one final product" }], ["planning", "assessment", "visual-thinking"])
      ]
    },
    "design-technology": {
      identity: "D&T connects user, purpose, technical knowledge, making, testing and improvement.", bigIdeas: ["Products respond to users", "Function follows technical decisions", "Materials have properties", "Testing drives improvement"], knowledgeTypes: ["user", "technical", "material", "procedural"], progression: ["state a simple purpose", "build testable criteria", "select mechanisms and materials", "iterate against evidence"], teacherReminders: ["Do not turn D&T into decorative craft", "Test against criteria, not personal liking"],
      profiles: [profile("design", "Design for a user", ["user", "purpose", "criteria", "design"], "Translate a user's need into testable criteria and alternative design decisions.", "A design criterion describes successful function rather than a feature to copy.", ["user", "purpose", "criteria", "function", "constraint"], ["The first sketch is the design", "Criteria describe decoration"], [{ name: "User–need–criterion map", use: "before generating design possibilities", avoid: "when it pre-selects the solution" }], ["planning", "reasoning", "representation"]), profile("making", "Make, test and improve", ["make", "material", "join", "test", "improve"], "Select processes, make accurately and use test evidence to improve.", "A well-made product can still fail its purpose.", ["property", "accurate", "test", "evaluate", "redesign"], ["Neat equals successful", "Evaluation comes only at the end"], [{ name: "Specification test table", use: "when criteria can produce observable evidence", avoid: "when ratings replace explanation" }], ["executive-function", "assessment", "metacognition"])]
    },
    music: {
      identity: "Music is learned through attentive listening, sounding, performing, composing and refining.", bigIdeas: ["Pulse organises time", "Pitch shapes melody", "Timbre and texture shape sound", "Structure makes musical ideas coherent"], knowledgeTypes: ["aural", "performative", "compositional", "notational"], progression: ["imitate and maintain", "notice and name", "combine and vary", "compose, rehearse and evaluate"], teacherReminders: ["Keep written demand below musical demand", "Hear and perform before notating"],
      profiles: [profile("perform", "Listen and perform", ["listen", "perform", "pulse", "rhythm", "pitch"], "Coordinate listening, pulse, part and expressive intention in real time.", "Accuracy serves shared musical meaning, not mechanical repetition.", ["pulse", "rhythm", "pitch", "timbre", "ensemble"], ["Faster is more fluent", "Louder is higher"], [{ name: "Listening map", use: "to direct attention across time", avoid: "when reading the map replaces listening" }], ["executive-function", "visual-thinking", "assessment"]), profile("compose", "Compose and refine", ["compose", "motif", "structure", "rehearse"], "Generate, select, organise and develop sound for an intended effect.", "A constraint opens choices; it should not pre-compose the music.", ["motif", "structure", "contrast", "develop", "refine"], ["Composition starts with notation", "More ideas automatically improve a piece"], [{ name: "Motif development path", use: "when one idea needs purposeful variation", avoid: "as a fixed required sequence" }], ["planning", "metacognition", "representation"])]
    },
    "physical-education": {
      identity: "PE develops physical competence and intelligent movement through high-activity practice, decisions and concise feedback.", bigIdeas: ["Balance and control underpin movement", "Perception guides action", "Tactics respond to context", "Practice is deliberate"], knowledgeTypes: ["physical", "tactical", "procedural", "reflective"], progression: ["explore movement", "stabilise one cue", "apply under changing conditions", "select, adapt and evaluate"], teacherReminders: ["Use one or two distance-legible cues", "Do not replace practice with worksheet completion"],
      profiles: [profile("movement", "Movement and performance", ["movement", "skill", "dance", "gymnastics", "sequence"], "Perform, observe and refine one visible movement feature.", "A cue should focus attention, not describe the entire body.", ["balance", "control", "sequence", "transition", "accuracy"], ["More cues create faster improvement", "One model is the only successful form"], [{ name: "Two-cue station card", use: "when cues must be visible while moving", avoid: "when text reduces activity time" }], ["visual-thinking", "assessment", "executive-function"]), profile("tactics", "Games and tactics", ["game", "tactic", "space", "team", "decision"], "Perceive space and relationships, choose an action, then evaluate its effect.", "Tactics are responsive principles rather than fixed moves.", ["space", "support", "transition", "possession", "tactic"], ["Good tactics never change", "The skilled player should always act alone"], [{ name: "If–notice–choose card", use: "between short game episodes", avoid: "as an on-field script" }], ["reasoning", "discussion", "metacognition"])]
    },
    languages: {
      identity: "Primary languages connect sound, meaning, pattern, interaction and cultural understanding.", bigIdeas: ["Sound systems differ", "Patterns generate new meanings", "Retrieval grows through use", "Communication is responsive"], knowledgeTypes: ["phonological", "lexical", "grammatical", "cultural"], progression: ["hear and imitate", "recognise and retrieve", "substitute meaningfully", "interact and create"], teacherReminders: ["Do not invent English-style pronunciation spellings", "Check generated language with a trusted source"],
      profiles: [profile("language", "Sound, sentence and interaction", ["language", "French", "Spanish", "German", "sentence", "listen", "speak"], "Hear accurately, retrieve language and manipulate known patterns for a communicative purpose.", "Substitution creates meaning only when grammar, sound and agreement remain accurate.", ["sound", "phrase", "pattern", "agreement", "question"], ["English sound values transfer directly", "Word-for-word substitution always works"], [{ name: "Substitution strip", use: "when choices are grammatically compatible and meaningful", avoid: "when it permits inaccurate combinations" }], ["language", "vocabulary", "discussion"])]
    },
    "religious-education": {
      identity: "RE develops secure knowledge of religion and non-religion, careful interpretation and reasoned reflection within the applicable syllabus.", bigIdeas: ["Worldviews are lived and interpreted", "Traditions contain diversity", "Texts and artefacts need context", "Questions can be examined through different ways of knowing"], knowledgeTypes: ["substantive", "disciplinary", "personal"], progression: ["encounter examples", "notice context and diversity", "compare interpretations", "form reasoned accounts"], teacherReminders: ["Follow the school's agreed or trust syllabus", "Never ask a pupil to speak for a community"],
      profiles: [profile("worldviews", "Religion and worldviews", ["belief", "religion", "worldview", "practice", "sacred", "ethic"], "Use contextual evidence to understand beliefs, practices, interpretations and lived diversity.", "An example illuminates a worldview but cannot represent every member.", ["worldview", "belief", "practice", "interpretation", "diversity"], ["All believers practise identically", "One artefact speaks for a whole tradition"], [{ name: "Belief–practice–context map", use: "to explore possible relationships", avoid: "when arrows imply one universal causal route" }], ["knowledge", "reasoning", "comparison"])]
    },
    pshe: {
      identity: "PSHE and Relationships Education build knowledge, language and safe decision-making without requiring personal disclosure.", bigIdeas: ["Relationships involve respect and boundaries", "Help-seeking is a learnable route", "Emotions carry information", "Online actions have contexts and consequences"], knowledgeTypes: ["relational", "health", "safety", "decision"], progression: ["name and recognise", "rehearse through neutral scenarios", "compare choices and consequences", "identify support routes"], teacherReminders: ["Use fictional or third-person scenarios", "Keep classroom teaching distinct from therapeutic support"],
      profiles: [profile("relationships", "Relationships, health and safety", ["relationship", "friend", "emotion", "boundary", "online", "safety", "help"], "Interpret a neutral scenario, consider safe choices and identify a route to help.", "A strategy supports an everyday situation; it does not replace trusted adult or professional help.", ["respect", "boundary", "strategy", "trusted adult", "report"], ["Pupils must share personal experiences", "One response fits every context"], [{ name: "Notice–choice–consequence route", use: "with fictional age-appropriate scenarios", avoid: "when it solicits or displays personal disclosure" }], ["reasoning", "planning", "vocabulary"])]
    }
  };
  Object.assign(DATA.subjectBrains, brains);

  const E = (id, name, subjects, family, barriers, layout, purpose, preserves, risk, prompts, diagram = "", formats = ["workpage", "table-card"]) => ({
    id, name, tagline: purpose, subjects, family, barriers, layout, bestFor: purpose, preserves, risk, prompts, diagram, formats,
    distinctive: `${layout.replaceAll("-", " ")} composed from editable prompts, examples and response structures`,
    lessonPhases: ["Before the lesson", "Teacher modelling", "Guided practice", "Independent practice", "Review and reflection"]
  });

  const enrich = {
    "vocabulary-builder": ["word-cards", "Use and connect a small set of essential words.", "the pupil's choice of precise language", "Too many entries become a wall of words.", ["Explain it precisely", "Use it in context", "Contrast it with a non-example"]],
    "vocabulary-network": ["network", "Reveal meaningful relationships between words and concepts.", "the pupil's explanation of each connection", "A pre-filled network can conceal insecure meaning.", ["Name the central idea", "Connect two words", "Explain the strongest link"], "concept-map"],
    "inference-bridge": ["bridge", "Connect precise evidence, relevant knowledge and a warranted inference.", "the inference and the evidence judgement", "A stem can quietly supply the conclusion.", ["Notice exactly", "Bring relevant knowledge", "Infer and test"]],
    "paragraph-planner": ["sequence", "Hold paragraph purpose and development lightly.", "authorial content, order and wording", "A rigid frame can produce identical writing.", ["Name the paragraph purpose", "Select the central idea", "Develop and connect"]],
    "sentence-ladder": ["ladder", "Expand or combine only where meaning improves.", "the writer's grammatical and vocabulary choices", "Longer can be mistaken for better.", ["Write the core idea", "Add a meaningful relationship", "Reread for effect"]],
    "worked-example": ["worked", "Make expert decisions visible, then fade them deliberately.", "transfer to a parallel example", "The model may reveal the answer or invite copying.", ["Study the decision", "Complete the next move", "Explain what transfers"]],
    "representation-selector": ["choice", "Compare representations by what they reveal and conceal.", "the choice and evaluation of a representation", "A familiar model may be used decoratively.", ["What must become visible?", "Compare two models", "Choose and justify"]],
    "reasoning-ladder": ["ladder", "Move from noticing to a defensible conclusion.", "the central relationship and justification", "Too many steps may fragment fluent reasoning.", ["Notice", "Connect", "Justify", "Test"]],
    "observation-recorder": ["quadrant", "Separate observation, measurement and inference.", "the interpretation of evidence", "A recording frame may imply all observations matter equally.", ["Observe or measure", "Notice a pattern", "Infer cautiously"]],
    "evidence-builder": ["chain", "Build a claim–evidence–reasoning chain.", "the claim and warrant", "A supplied claim makes evidence selection cosmetic.", ["Form a claim", "Select evidence", "Explain the warrant"]],
    "chronology-builder": ["timeline", "Coordinate sequence, duration, change and continuity.", "selection and interpretation of events", "An evenly spaced timeline may imply a false scale.", ["Place securely", "Mark proportional status", "Explain change across time"], "timeline"],
    "comparison-organiser": ["compare", "Compare through a shared disciplinary criterion.", "the criterion and significance of the comparison", "Two lists are not yet a comparison.", ["Set a criterion", "Inspect both cases", "Form a meaningful comparison"]],
    "algorithm-planner": ["flow", "Plan precise logic before selecting code syntax.", "algorithmic decisions and testing", "A completed sequence becomes code to copy.", ["Define the goal", "Sequence the logic", "Test a case"], "flowchart"],
    "metacognition-planner": ["cycle", "Plan, monitor and evaluate a subject-specific approach.", "choice of strategy and self-evaluation", "Generic prompts can become a compliance checklist.", ["Plan a route", "Monitor against the goal", "Evaluate and adapt"]],
    "vocabulary-preteach": ["word-cards", "Prepare a few high-leverage words for recognition and use.", "meaning-making inside the lesson", "Pre-teaching every unfamiliar word creates overload.", ["Hear and say", "Connect meaning", "Use and retrieve"]]
  };

  DATA.engines = DATA.engines.map(engine => {
    const [layout, purpose, preserves, risk, prompts, diagram = ""] = enrich[engine.id];
    return { ...engine, family: engine.family || (engine.id.includes("vocabulary") ? "vocabulary" : engine.id === "algorithm-planner" ? "planning" : engine.id === "worked-example" ? "knowledge" : "reasoning"), layout, bestFor: purpose, tagline: purpose, preserves, risk, prompts, diagram, formats: ["workpage", "table-card", "desk-strip"], lessonPhases: DATA.lessonPhases };
  });

  const extraEngines = [
    E("background-primer", "Background Knowledge Primer", ["english", "history", "science", "geography"], "knowledge", ["knowledge", "reading"], "primer", "Activate only the knowledge needed to enter a text or task.", "new interpretation and retrieval decisions", "Too much background knowledge can pre-interpret the text.", ["Recall the anchor idea", "Connect it to today's context", "Name what remains uncertain"]),
    E("fluency-marker", "Fluency Phrase Marker", ["english"], "language", ["reading", "working-memory"], "phrase-strip", "Make syntax and meaningful phrasing audible in a short passage.", "accurate reading for meaning", "Permanent phrase marks can prevent independent parsing.", ["Listen to a model", "Mark meaningful phrases", "Reread and compare"]),
    E("retrieval-locator", "Retrieval Locator", ["english"], "knowledge", ["reading", "attention"], "locator", "Locate information efficiently without answering the question.", "selection and interpretation of the located detail", "Location cues can leak the answer.", ["Name what the question seeks", "Choose the likely text region", "Verify the exact detail"]),
    E("summary-shrinker", "Summary Shrinker", ["english", "history", "science"], "reasoning", ["organisation", "reading"], "shrinker", "Reduce a text or explanation while preserving its central meaning.", "judgement of importance", "A word limit alone rewards deletion rather than synthesis.", ["State the whole meaning", "Remove repetition", "Keep only indispensable detail"]),
    E("oral-rehearsal", "Oral Rehearsal Builder", ["english", "languages", "science", "history"], "discussion", ["writing", "vocabulary", "explanation"], "dialogue", "Rehearse, hear and improve an idea before recording.", "choice of content and final wording", "A script can replace genuine talk.", ["Say the idea", "Partner paraphrases", "Repeat with one improvement"]),
    E("audience-purpose", "Audience and Purpose Planner", ["english"], "planning", ["planning", "organisation"], "decision-board", "Connect audience, purpose and effect to compositional decisions.", "the writer's content and voice", "Feature lists can replace authorial purpose.", ["Name the intended effect", "Choose content", "Shape voice and structure"]),
    E("model-text-noticer", "Model Text Noticer", ["english"], "assessment", ["reading", "writing"], "noticer", "Notice transferable writer decisions in a model text.", "application in a new context", "Imitation may become copying of surface features.", ["Notice a choice", "Explain its effect", "Decide whether it fits your writing"]),
    E("revision-lens", "Revision Lens", ["english"], "metacognition", ["self-monitoring", "writing"], "lens", "Reread through one purposeful lens and evaluate a change.", "the writer's judgement about revision", "A long checklist disperses attention.", ["Name intended effect", "Locate a mismatch", "Change and compare"]),
    E("morphology-tree", "Morphology Tree", ["english", "languages"], "vocabulary", ["vocabulary", "knowledge"], "tree", "Use roots and affixes to connect spelling and meaning.", "reasoned word construction", "Unrelated exception words do not fit the tree.", ["Identify the root", "Add a meaningful affix", "Explain meaning and spelling"], "classification-tree"),
    E("spelling-decision", "Spelling Decision Path", ["english"], "metacognition", ["self-monitoring", "writing"], "flow", "Coordinate sound, spelling pattern and morphology.", "the final spelling choice and explanation", "A path can imply one strategy fits every word.", ["Say and segment", "Look for word parts", "Choose, check and explain"], "flowchart"),
    E("part-whole", "Part–Whole Builder", ["mathematics"], "representation", ["conceptual", "representation"], "math-model", "Expose additive composition without choosing the calculation for the pupil.", "identification of known and unknown relationships", "A model can pre-label the operation.", ["Identify the whole", "Place known parts", "Mark the unknown"], "part-whole"),
    E("place-value", "Place Value Representation", ["mathematics"], "representation", ["conceptual", "representation"], "math-model", "Coordinate digit, place, value and exchange.", "interpretation of base-ten structure", "A chart alone may hide magnitude.", ["Name the unit", "Compose or exchange", "Connect representation to notation"], "place-value"),
    E("number-line", "Number Line Constructor", ["mathematics"], "representation", ["representation", "conceptual"], "math-model", "Construct a scaled line that reveals magnitude and interval.", "choice of scale, endpoints and labels", "Unequal spacing creates a false relationship.", ["Set endpoints", "Choose an interval", "Place and justify values"], "number-line"),
    E("array-grouping", "Array and Grouping Model", ["mathematics"], "representation", ["conceptual", "reasoning"], "math-model", "Reveal equal groups, factors and commutativity.", "the multiplicative relationship", "Arrays can distort continuous scaling.", ["Define one group", "Arrange equal rows and columns", "Connect equations"], "array"),
    E("bar-model", "Bar Model Builder", ["mathematics"], "representation", ["representation", "reasoning"], "math-model", "Represent additive or multiplicative relationships when bars reveal the unknown.", "selection of operation and solution", "A bar model is not useful for every word problem.", ["Name quantities", "Show the relationship", "Mark known and unknown"], "bar-model"),
    E("fraction-strip", "Fraction Strip Builder", ["mathematics"], "representation", ["conceptual", "representation"], "math-model", "Compare fractions against the same whole.", "reasoning about unit fraction and equivalence", "Unequal wholes invalidate the comparison.", ["Fix the whole", "Partition equally", "Compare or transform"], "fraction-strip"),
    E("ratio-table", "Ratio Table Builder", ["mathematics"], "representation", ["reasoning", "organisation"], "table", "Track covariation and scale between linked quantities.", "choice of multiplicative relationship", "Additive jumps may be hidden as multiplicative thinking.", ["Name both quantities", "Record a known pair", "Scale and explain"]),
    E("incomplete-example", "Incomplete Example Builder", ["mathematics", "computing"], "assessment", ["self-monitoring", "working-memory"], "worked", "Complete only the missing expert decision in a partially worked example.", "diagnosis of the missing move", "The surrounding example may reveal too much.", ["Inspect completed moves", "Locate the decision gap", "Complete and justify"]),
    E("error-spotter", "Error Spotter", ["mathematics", "computing", "english"], "assessment", ["self-monitoring", "conceptual"], "error", "Diagnose an error before repairing it.", "the explanation and correction", "Marking the exact error can remove diagnosis.", ["Predict the intended outcome", "Find first divergence", "Repair and retest"]),
    E("known-unknown", "Known and Unknown Mapper", ["mathematics", "science"], "planning", ["planning", "reasoning"], "map", "Separate given, derived and unknown quantities or claims.", "choice of a solution route", "Sorting data can imply every detail matters.", ["List what is known", "Name what must be found", "Connect only relevant information"]),
    E("problem-sorter", "Problem Structure Sorter", ["mathematics"], "reasoning", ["conceptual", "reasoning"], "sort", "Compare problems by mathematical structure rather than surface story.", "classification and operation choice", "Keywords can reappear as a false sorting rule.", ["Hide the numbers", "Name the relationship", "Sort and defend"]),
    E("plan-solve-check", "Plan Solve Check", ["mathematics"], "metacognition", ["planning", "self-monitoring"], "cycle", "Externalise a concise problem-solving cycle.", "strategy choice and checking method", "A fixed cycle can become procedural compliance.", ["Plan from structure", "Solve and annotate choices", "Check differently"]),
    E("systematic-listing", "Systematic Listing Grid", ["mathematics", "computing"], "executive-function", ["organisation", "working-memory"], "table", "Record cases systematically without deciding which cases exist.", "the completeness argument", "A pre-filled grid can supply the search space.", ["Choose an organising rule", "Record without repetition", "Prove completeness"]),
    E("always-sometimes-never", "Always Sometimes Never", ["mathematics", "science", "grammar"], "reasoning", ["reasoning", "conceptual"], "decision-board", "Test the scope of a general statement using examples and proof.", "classification and justification", "One example cannot prove an always claim.", ["Test a typical case", "Seek a boundary case", "Justify the classification"]),
    E("generalisation-ladder", "Generalisation Ladder", ["mathematics", "science"], "reasoning", ["reasoning", "explanation"], "ladder", "Move from examples to a precise general statement.", "the generalisation and its justification", "Sentence stems can write the rule for pupils.", ["Notice what varies", "State what stays", "Generalise and test"]),
    E("counterexample", "Counterexample Prompt", ["mathematics", "science", "computing"], "reasoning", ["reasoning", "self-monitoring"], "challenge", "Search deliberately for one case that disproves a claim.", "construction and explanation of the counterexample", "An over-specific prompt can reveal the case.", ["Define what would disprove", "Search boundary cases", "Explain why the claim fails"]),
    E("enquiry-selector", "Enquiry Type Selector", ["science"], "planning", ["planning", "conceptual"], "choice", "Choose an enquiry form that matches the scientific question.", "selection of method and evidence", "Every enquiry must not be forced into a fair test.", ["Name the question", "Compare enquiry types", "Choose evidence needed"]),
    E("classification-key", "Classification Key Builder", ["science"], "reasoning", ["conceptual", "organisation"], "tree", "Create discriminatory questions from observable characteristics.", "choice and ordering of criteria", "A key may use inferred or subjective features.", ["Choose an observable difference", "Split into two groups", "Test every path"], "classification-tree"),
    E("variable-selector", "Variable Selector", ["science"], "planning", ["planning", "vocabulary"], "table", "Identify variables only where a comparative test requires them.", "method design and control decisions", "The frame is unsuitable for observation, research or classification enquiries.", ["Confirm comparative test", "Choose what changes and is measured", "Justify controls"]),
    E("method-sequencer", "Method Sequencer", ["science", "design-technology"], "executive-function", ["working-memory", "planning"], "sequence", "Sequence a safe, repeatable method without pre-writing the conclusion.", "procedural decisions and observations", "A complete recipe can remove method thinking.", ["Match equipment to action", "Order safely", "Check repeatability"]),
    E("results-table", "Results Table Builder", ["science", "geography"], "recording", ["organisation", "representation"], "table", "Build headings, units and repeats around the evidence needed.", "recording and interpretation of results", "A supplied table may impose the wrong data structure.", ["Name variables or categories", "Add units", "Plan repeats or samples"]),
    E("pattern-noticer", "Pattern Noticer", ["science", "geography", "mathematics"], "reasoning", ["reasoning", "attention"], "noticer", "Describe a pattern before explaining it.", "selection of relevant evidence and scientific explanation", "Prompts can encourage a trend where data is inconclusive.", ["Describe without explanation", "Cite evidence", "Offer a cautious explanation"]),
    E("explanation-chain", "Scientific Explanation Chain", ["science"], "reasoning", ["explanation", "conceptual"], "chain", "Connect phenomenon, evidence, scientific idea and mechanism.", "the causal mechanism", "A causal stem may state the answer.", ["Name the phenomenon", "Select relevant evidence", "Explain the mechanism"]),
    E("evaluation-card", "Evaluation and Improvement Card", ["science"], "assessment", ["self-monitoring", "reasoning"], "lens", "Evaluate evidence quality and propose a justified improvement.", "judgement of limitations", "Generic 'human error' prompts weaken evaluation.", ["Name the limitation", "Explain its effect", "Propose a targeted improvement"]),
    E("source-observation", "Source Observation Frame", ["history"], "reasoning", ["reading", "reasoning"], "source", "Move from source observation to contextual historical inference.", "the inference and limits of the source", "The source must not be treated as transparent truth.", ["Observe precisely", "Add period knowledge", "Infer and identify limits"]),
    E("provenance-prompt", "Provenance Prompt", ["history"], "knowledge", ["reasoning", "knowledge"], "source", "Use creator, date, context and purpose to refine what a source can reveal.", "judgement of usefulness for a question", "Reliable/unreliable labels oversimplify evidence.", ["Who, when and where?", "Why might it exist?", "Useful for which question?"]),
    E("cause-consequence", "Cause and Consequence Chain", ["history"], "reasoning", ["reasoning", "chronology"], "causal-chain", "Connect conditions, triggers, mechanisms and consequences across time.", "selection and weighting of causes", "A linear chain can hide interacting factors.", ["Separate condition and trigger", "Trace mechanism", "Compare consequence and significance"], "causal-chain"),
    E("interpretation-compare", "Interpretation Comparison", ["history", "religious-education"], "comparison", ["comparison", "reasoning"], "compare", "Compare reasoned accounts against evidence and context.", "evaluation rather than preference", "A grid may imply there are only two interpretations.", ["State each interpretation", "Test against evidence", "Explain difference and limits"]),
    E("significance-criteria", "Significance Criteria", ["history"], "reasoning", ["reasoning", "comparison"], "decision-board", "Judge historical significance through explicit, contestable criteria.", "selection and weighting of criteria", "Pre-selected criteria can pre-determine the judgement.", ["Propose a criterion", "Test it with evidence", "Weigh and justify"]),
    E("location-ladder", "Location Ladder", ["geography"], "knowledge", ["knowledge", "vocabulary"], "ladder", "Locate a place through nested spatial scales.", "geographical description and significance", "A place can be reduced to coordinates and labels.", ["Locate within locality", "Connect region and country", "Explain why scale matters"]),
    E("map-symbol", "Map Symbol and Orientation Guide", ["geography"], "representation", ["representation", "vocabulary"], "map", "Decode and use symbols, direction, scale and grid deliberately.", "interpretation of spatial evidence", "A decorative map may lack usable scale or orientation.", ["Check key and north", "Locate using grid or coordinates", "Use scale to interpret"]),
    E("fieldwork-planner", "Fieldwork Question Planner", ["geography"], "planning", ["planning", "organisation"], "decision-board", "Align a located question, sample, method and evidence.", "fieldwork decisions and evaluation", "A complete plan may conceal why a method fits.", ["Frame a located question", "Choose sample and method", "Anticipate limits"]),
    E("place-comparison", "Place Comparison Builder", ["geography"], "comparison", ["comparison", "knowledge"], "compare", "Compare places through shared processes, scale and evidence.", "geographical explanation", "Fact lists encourage stereotypes and false binaries.", ["Set a geographical criterion", "Use located evidence", "Explain pattern and difference"]),
    E("process-sequence", "Physical Process Sequence", ["geography", "science"], "reasoning", ["explanation", "organisation"], "cycle", "Sequence a physical process while preserving causal mechanism.", "explanation of change", "Arrows can suggest inevitability or omit feedback.", ["Name initial condition", "Trace each process", "Explain outcome and variation"], "cycle"),
    E("decomposition", "Decomposition Planner", ["computing", "design-technology"], "planning", ["planning", "working-memory"], "tree", "Break a goal into coherent sub-problems before implementation.", "choice of decomposition", "Pre-filled parts can define the solution.", ["Define the whole goal", "Identify independent sub-problems", "Check interfaces"]),
    E("trace-table", "Code Trace Table", ["computing"], "representation", ["working-memory", "conceptual"], "table", "Make changing program state visible across steps.", "prediction and explanation of output", "A trace table is unnecessary for simple stateless sequences.", ["Record initial state", "Execute one instruction", "Update and explain"]),
    E("debug-ladder", "Debugging Ladder", ["computing"], "metacognition", ["self-monitoring", "planning"], "ladder", "Use expected and actual behaviour to test one hypothesis.", "diagnosis and chosen test", "Naming the faulty line removes debugging.", ["State expected outcome", "Locate first divergence", "Change one thing and retest"]),
    E("input-output", "Input Process Output", ["computing", "science"], "representation", ["conceptual", "organisation"], "flow", "Distinguish input, process, stored state and output.", "explanation of the system", "A three-box model may oversimplify feedback or networks.", ["Name the input", "Describe transformation", "Connect state and output"], "flowchart"),
    E("search-evaluation", "Search Evaluation Card", ["computing"], "reasoning", ["reading", "reasoning"], "lens", "Evaluate relevance, provenance, evidence and ranking of online information.", "judgement of usefulness and trust", "A checklist cannot guarantee truth.", ["Clarify the search need", "Inspect source and evidence", "Compare before deciding"]),
    E("visual-element", "Visual Element Explorer", ["art"], "visual-thinking", ["attention", "vocabulary"], "noticer", "Direct looking towards line, shape, tone, colour, texture and space.", "the pupil's interpretation and artistic choice", "A checklist can flatten open looking.", ["Notice one element", "Describe its effect", "Connect to your own possibility"]),
    E("material-exploration", "Material Exploration Grid", ["art", "design-technology"], "assessment", ["planning", "self-monitoring"], "test-grid", "Test materials and processes before selecting for an intention.", "choice of material and effect", "Ratings can replace tactile observation.", ["Try one controlled variation", "Record the effect", "Choose for a reason"]),
    E("design-criteria", "Design Criteria Builder", ["design-technology"], "planning", ["planning", "reasoning"], "decision-board", "Turn user and purpose into testable design criteria.", "generation of design solutions", "Criteria can become a list of copied features.", ["Name user and purpose", "Write testable criteria", "Check criteria do not prescribe form"]),
    E("product-test", "Test Against Specification", ["design-technology"], "assessment", ["self-monitoring", "reasoning"], "table", "Collect evidence against functional criteria and redesign.", "evaluation and improvement decisions", "Personal preference can masquerade as test evidence.", ["Test one criterion", "Record evidence", "Improve the cause of failure"]),
    E("listening-map", "Listening Map", ["music"], "visual-thinking", ["attention", "working-memory"], "timeline", "Track structure, texture, dynamics or motif across real listening time.", "aural noticing and interpretation", "Reading the map can replace listening.", ["Choose one listening lens", "Mark change over time", "Explain musical effect"]),
    E("motif-development", "Motif Development", ["music"], "planning", ["planning", "self-monitoring"], "sequence", "Vary and organise one musical idea through sound.", "compositional selection", "A required set of transformations can pre-compose the outcome.", ["Perform the motif", "Try one variation", "Select, structure and rehearse"]),
    E("skill-cue", "Skill Cue Card", ["physical-education"], "executive-function", ["attention", "self-monitoring"], "cue-card", "Keep one or two observable movement cues visible during practice.", "physical problem-solving and movement", "Dense text reduces active practice and overloads attention.", ["One cue before moving", "Practise under one condition", "Partner notices the cue"]),
    E("tactical-decision", "Tactical Decision Prompt", ["physical-education"], "reasoning", ["attention", "reasoning"], "decision-board", "Link what a player notices to a responsive tactical choice.", "perception and decision in play", "A fixed move removes tactical adaptation.", ["Notice space and people", "Choose an action", "Review its effect"]),
    E("sentence-strip", "Sentence Building Strip", ["languages"], "language", ["vocabulary", "writing"], "substitution", "Combine compatible language chunks accurately for new meanings.", "choice of meaning and accurate agreement", "Incompatible choices can generate false language.", ["Hear the base pattern", "Substitute one compatible chunk", "Say, check and write"]),
    E("conversation-path", "Conversation Role Card", ["languages"], "discussion", ["explanation", "attention"], "dialogue", "Support responsive listening and short exchanges.", "choice of response and follow-up", "A memorised script is not interaction.", ["Listen for the key information", "Respond meaningfully", "Ask or extend"]),
    E("worldview-compare", "Worldview Comparison", ["religious-education"], "comparison", ["comparison", "knowledge"], "compare", "Compare contextual examples while representing diversity within traditions.", "interpretation of similarity and difference", "One example must not stand for every member.", ["Locate each example", "Compare through one concept", "Name diversity and limits"]),
    E("artefact-enquiry", "Artefact Enquiry", ["religious-education"], "reasoning", ["attention", "reasoning"], "source", "Move from observation to contextual questions and cautious interpretation.", "questions and interpretation", "An artefact cannot speak for a whole worldview.", ["Observe without assumption", "Ask context questions", "Interpret with evidence and limits"]),
    E("help-seeking", "Help-Seeking Route", ["pshe"], "planning", ["planning", "vocabulary"], "route", "Rehearse safe routes to trusted adult help through neutral scenarios.", "choice of safe action", "The resource must never solicit personal disclosure.", ["Notice a need for help", "Name safe options", "Choose how to tell a trusted adult"]),
    E("communication-choice", "Communication Choice", ["pshe"], "reasoning", ["vocabulary", "reasoning"], "scenario", "Compare respectful, boundaried responses to fictional situations.", "the pupil's judgement and language choice", "One script cannot fit every relationship or safety context.", ["Read the neutral scenario", "Compare possible responses", "Choose and explain a safe option"])
  ];

  extraEngines.forEach(engine => {
    if (!DATA.engines.some(item => item.id === engine.id)) DATA.engines.push(engine);
  });

  const formatAdditions = [
    { id: "a5-sheet", name: "A5 pupil sheet", group: "Write", note: "A genuinely reflowed half-page scaffold.", pieces: 1 },
    { id: "cut-cards", name: "Cut-out prompt cards", group: "Prompt", note: "Four, six or eight discreet cards with cut lines.", pieces: 6 },
    { id: "mini-booklet", name: "Mini-booklet", group: "Sequence", note: "A short folded pathway with one decision per page.", pieces: 4 },
    { id: "modelling-page", name: "Teacher modelling page", group: "Teach", note: "Large annotated prompts for live modelling.", pieces: 1 },
    { id: "presentation-board", name: "Presentation board", group: "Display", note: "Distance-legible sequence for a classroom screen.", pieces: 1 },
    { id: "intervention-pack", name: "Intervention pack", group: "Teach", note: "Teacher introduction, pupil pages and fade check.", pieces: 4 },
    { id: "home-support", name: "Home-learning support", group: "Share", note: "Plain-language pupil and adult guidance without answers.", pieces: 2 },
    { id: "mixed-pack", name: "Growth pathway pack", group: "Differentiate", note: "Discreet Seed, Sprout, Growth and Independent versions.", pieces: 4 }
  ];
  formatAdditions.forEach(format => {
    if (!DATA.printFormats.some(item => item.id === format.id)) DATA.printFormats.push(format);
  });

  DATA.aiTasks = [
    ["accurate-examples", "Generate accurate examples"], ["source-text", "Draft a short source text"],
    ["questions", "Generate additional questions"], ["scenario-cards", "Create scenario cards"],
    ["vocabulary", "Improve vocabulary explanations"], ["model-answers", "Create model and non-model answers"],
    ["misconceptions", "Suggest misconceptions"], ["illustration-brief", "Generate an illustration brief"],
    ["language-clarity", "Adapt instruction clarity"], ["extra-practice", "Create extra practice"],
    ["accuracy-check", "Check subject accuracy"], ["critique", "Critique the scaffold"],
    ["teacher-guidance", "Create teacher guidance"]
  ].map(([id, name]) => ({ id, name }));

  DATA.build3 = {
    version: 3,
    designDecisions: ["intended learning", "essential thinking", "barrier", "support mechanism", "pupil action", "removal pathway"],
    instructionModes: ["standard", "shorter", "one-at-a-time", "explicit", "read-aloud"],
    densityModes: ["calm", "reduced", "spacious"],
    printModes: ["colour", "low-colour", "greyscale", "black-white", "high-contrast"],
    groupCodes: ["Path A", "Path B", "Path C", "Path D"]
  };
})();
